#' App methods tab
#'
#' @return NULL
#' @export
tab_methods <- function(){
  shiny::tabPanel(
    "Methods",
    shiny::fluidPage(

      shiny::h2("Methods and modelling approaches"),

      # --- SECTION I ---
      shiny::tags$h3("I. Modelling Framework"),

      shiny::tags$p(
        "The analyses presented here rely on aggregated outputs from two malaria transmission models: ",
        shiny::tags$a(shiny::tags$b("malariasimulation"), href = "https://mrc-ide.github.io/malariasimulation/", target = "_blank"),
        " and ",
        shiny::tags$a(shiny::tags$b("OpenMalaria. "), href = "https://github.com/SwissTPH/openmalaria", target = "_blank"),
        "Each model explored future scenarios to assess the impact of a suite of malaria intervention packages ",
        "at the subnational level (admin 1 regions) across sub-Saharan Africa."
      ),

      shiny::tags$p(
        "Both models were calibrated and customised such that they are representative of,
        sub-national variation across sub-Saharan Afrca, incorporating context-specific factors ",
        "that influence historical infection patterns, intervention impact, and observed malaria prevalence."
      ),

      shiny::tags$img(src = "modelling_approach.png",
                      width = "100%",
                      style = "max-width:600px; border-radius:8px; margin:10px 0;"),
      shiny::tags$br(),
      shiny::tags$b("Figure 1. Schematic representation of the modelling approach: taking calibrated, context-specific
                      settings and modelling the impact and cost of future intervetion scenarios"
      ),

      shiny::tags$br(),

      # --- SECTION II ---
      shiny::tags$h3("II. Interventions Assessed"),

      shiny::tags$p(
        "The following interventions were evaluated in all possible combinations, starting from the strategy currently implemented ",
        "in each administrative unit (the ",
        shiny::tags$b("Business as Usual (BAU)"),
        "), with its corresponding coverage levels. Scenarios were generated by adding new interventions or increasing ",
        "the coverage of existing ones:"
      ),

      shiny::tags$ul(
        shiny::tags$li("Insecticide-treated bed nets (ITNs), including introduction and scale-up"),
        shiny::tags$li("Chemoprevention: Seasonal (SMC) or perennial (PMC)"),
        shiny::tags$li("Indoor residual spraying (IRS)"),
        shiny::tags$li("Vaccine"),
        shiny::tags$li("Case management(CM)")
      ),

      shiny::tags$br(),

      # --- SECTION III ---
      shiny::tags$h3("III. Health Impact and Cost-Effectiveness"),

      shiny::tags$p(
        "To estimate the impact of each intervention package, results were compared against the BAU scenario."
      ),

      shiny::tags$b("Health outcomes evaluated:"),
      shiny::tags$ul(
        shiny::tags$li("Incidence: number of new malaria cases over time"),
        shiny::tags$li("Cases averted: reduction in malaria cases relative to the BAU"),
        shiny::tags$li("Deaths averted: reduction in malaria-related mortality relative to the BAU"),
        shiny::tags$li("DALYs averted: disability-adjusted life years gained through reduced morbidity and mortality")
      ),

      shiny::tags$p(
        "Health outcomes were estimated for three age groups (0 to 5 years, 5 to 15 years, and 15 years and above) ",
        "and across both short- and long-term time horizons."
      ),

      shiny::tags$p(
        "Costs for each intervention were derived from WHO estimates for intervention and case-management costs. ",
        "The most cost-effective intervention package at each budget level was identified using a frontier approach, ",
        "providing guidance on how to cost-effectively scale interventions up or down from current coverage levels."
      )
    )
  )
}
