tab_methods <- function(){
  shiny::tabPanel(
    "Methods",
    shiny::fluidPage(

      shiny::h2("Methods and modelling approaches"),

      # --- SECTION I ---
      shiny::tags$h3("I. Modelling Framework"),

      shiny::tags$p(
        "The analyses presented here rely on aggregated outputs from two malaria transmission models: ",
        shiny::tags$a(shiny::tags$b("malariasimulation"), href = "https://mrc-ide.github.io/malariasimulation/", target = "_blank"),
        " and ",
        shiny::tags$a(shiny::tags$b("OpenMalaria. "), href = "https://github.com/SwissTPH/openmalaria", target = "_blank"),
        "Each model explored future scenarios to assess the impact of a suite of malaria intervention packages ",
        "at the subnational level (admin 1 regions) across sub-Saharan Africa."
      ),

      shiny::tags$p(
        "Both models were calibrated and customised for individual admin 1 regions, incorporating context-specific factors ",
        "that influence historical infection patterns, intervention efficacy, and observed malaria prevalence."
      ),

      shiny::tags$div(
        style = "background-color:#f9f9f9; border-left:4px solid #0072B2; padding:10px; margin:20px 0; border-radius:6px;",
        shiny::tags$img(src = "modelling approach.png",
                        width = "100%",
                        style = "max-width:600px; border-radius:8px; margin:10px 0;"),
        shiny::tags$br(),
        shiny::tags$b("Figure 1. Schematic representation of the modelling approach at the admin 1 level: "),
        "Models are calibrated using global estimates from the Malaria Atlas Project to accurately represent each admin 1 region ",
        "and reproduce historical malaria burden trends. Calibrated models are then used to conduct scenario analyses ",
        "and assess cost-effectiveness at the admin 1 level."
      ),

      shiny::tags$br(),

      # --- SECTION II ---
      shiny::tags$h3("II. Interventions Assessed"),

      shiny::tags$p(
        "The following interventions were evaluated in all possible combinations, starting from the strategy currently implemented ",
        "in each administrative unit (the ",
        tags$b("Business as Usual (BAU)"),
        "), with its corresponding coverage levels. Scenarios were generated by adding new interventions or increasing ",
        "the coverage of existing ones:"
      ),

      shiny::tags$ul(
        shiny::tags$li("Insecticide-treated bed nets (ITNs)"),
        shiny::tags$li("Chemoprevention: Seasonal (SMC) or perennial (PMC)"),
        shiny::tags$li("Indoor residual spraying (IRS)"),
        shiny::tags$li("Vaccine"),
        shiny::tags$li("Case management(CM)")
      ),

      shiny::tags$br(),

      # --- SECTION III ---
      shiny::tags$h3("III. Health Impact and Cost-Effectiveness"),

      shiny::tags$p(
        "To estimate the impact of each intervention package, results were compared against the BAU scenario."
      ),

      shiny::tags$b("Health outcomes evaluated:"),
      shiny::tags$ul(
        shiny::tags$li("Incidence – number of new malaria cases over time"),
        shiny::tags$li("Cases averted – reduction in malaria cases relative to the BAU"),
        shiny::tags$li("Deaths averted – reduction in malaria-related mortality relative to the BAU"),
        shiny::tags$li("DALYs averted – disability-adjusted life years gained through reduced morbidity and mortality")
      ),

      shiny::tags$p(
        "Health outcomes were estimated for three age groups (0–5 years, 5–15 years, and 15 years and above) ",
        "and across both short- and long-term time horizons."
      ),

      shiny::tags$p(
        "Costs for each intervention were derived from WHO estimates for intervention and case-management costs. ",
        "The most cost-effective intervention package at each budget level was identified using a frontier approach, ",
        "providing guidance on how to cost-effectively scale interventions up or down from current coverage levels."
      ),

      shiny::tags$br(),

      # --- SECTION IV ---
      shiny::tags$h3("IV. Setting Archetypes and Model Harmonisation"),

      shiny::tags$p(
        "Results from both models were harmonised and grouped into representative archetypes. ",
        "Each archetype captures common patterns in how optimal intervention strategies change with budget levels ",
        "across similar epidemiological settings."
      ),

      shiny::tags$p(
        "Simulations were run across a range of realistic scenarios, and settings showing similar decision-making trends ",
        "were aggregated. This allows general insights to be drawn — for example, identifying which intervention combinations ",
        "are consistently prioritised in settings with comparable transmission intensity, seasonality, and historical coverage."
      ),

      shiny::tags$div(
        style = "background-color:#fff3cd; border-left:4px solid #ffcc00; padding:12px; margin:25px 0; border-radius:6px;",
        shiny::tags$b("⚠️ Limitations"),
        shiny::tags$ul(
          shiny::tags$li("Aggregation of results smooths over local heterogeneities."),
          shiny::tags$li("Outputs are indicative and meant to inform, not prescribe, interventions.")
        )
      )
    )
  )
}
